name: Build Signed Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "cmdline-tools;latest" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Restore keystore from secrets
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > release.keystore
          ls -l release.keystore

      - name: Make gradlew executable
        run: |
          gradle wrapper
          chmod +x ./gradlew

      - name: Assemble Release (signed)
        run: |
          ./gradlew --no-daemon \
            -PRELEASE_KEYSTORE=release.keystore \
            -PRELEASE_KEYSTORE_PASSWORD="${{ secrets.KEYSTORE_PASSWORD }}" \
            -PRELEASE_KEY_ALIAS="${{ secrets.KEY_ALIAS }}" \
            -PRELEASE_KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}" \
            assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: ControlDeLanzamientos-Release-APK
          path: app/build/outputs/apk/release/app-release.apk
