name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "cmdline-tools;latest" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew --no-daemon assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: ControlDeLanzamientos-APK
          path: app/build/outputs/apk/debug/app-debug.apk

